[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Peridynamics = "4dc47793-80f3-4232-b30e-ca78ca9d621b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
VideoIO = "d6d074c3-1acf-5d4c-9a43-ef38773959a2"
